message: Order Service

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: order.events.fanout.exchange
        queue: event.stream
        terminal: order.axon.terminal
    rabbitmq:
        hostname: rabbitmq
        username: guest
        password: guest
    data:
        rest:
            #base-path: api/v1
logging:
    level:
        root: WARN
        org.springframework: INFO
        org.axonframework: INFO
    file: ./logs/order-service.log
