message: Order Service

#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
  application:
    exchange: order.events.fanout.exchange
    queue: order.default.queue
    databaseName: orders
    eventsCollectionName: events
    snapshotCollectionName: snapshots
  rabbitmq:
    hostname: rabbitmq
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://mongodb:27017/orders
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.axonframework: INFO
    com.cloudnative.reference: INFO
  file: ./build/logs/order-service.log
  
management:
  security:
    enabled: false
