message: Order Service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    application:
        exchange: order.events.fanout.exchange
        queue: order.default.queue
        eventsCollectionName: events
        snapshotCollectionName: snapshots
    rabbitmq:
        hostname: localhost
        username: guest
        password: guest

logging:
    level:
        root: INFO
        org.springframework: INFO
        org.axonframework: INFO
        com.cloudnative.reference: INFO
    file: ./build/logs/order-service.log
